[project]
name = "Bagshaw Fund"
version = "0.1.0"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "fastapi",
    "prisma",
    "pytz",
    "datetime",
    "polygon",
    "dotenv",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"